#!/usr/bin/env bash
# Configure Nginx so that its HTTP response contains a custom header (on web-01 and web-02)
# The name of the custom HTTP header must be X-Served-By
# The value of the custom HTTP header must be the hostname of the server Nginx is running on

# This script configures Nginx to include a custom HTTP header with the server hostname

# Update and install Nginx
sudo apt-get update
sudo apt-get -y install nginx

# Allow traffic through port 80 in the firewall
sudo ufw allow 'Nginx HTTP'

# Get the hostname of the server and add it to the custom HTTP header
hostname=$(curl http://169.254.169.254/latest/meta-data/local-hostname)
header_string="add_header X-Served-By $hostname;"
sudo sed -i "/server_name _;/a $header_string" /etc/nginx/sites-available/default

# Restart Nginx to apply the changes
sudo systemctl restart nginx

