#!/usr/bin/env bash
# Create a script to install and configure HAProxy on lb-01 server
# Configure HAProxy to send traffic to web-01 and web-02 servers
# Distribute requests using a roundrobin algorithm
# Make sure that HAProxy can be managed via an init script
# Install and configure HAproxy on my lb-01 server.

# Set student ID
STUDENT_ID=129817

# Update package lists
sudo apt-get update

# Install HAProxy
sudo apt-get install -y haproxy

# Configure HAProxy to send traffic to web-01 and web-02 servers
sudo bash -c "cat >/etc/haproxy/haproxy.cfg <<EOF
frontend http-in
    bind *:80
    default_backend servers

backend servers
    balance roundrobin
    server ${STUDENT_ID}-web-01 ${STUDENT_ID}-web-01:80 check
    server ${STUDENT_ID}-web-02 ${STUDENT_ID}-web-02:80 check
EOF"

# Make sure that HAProxy can be managed via an init script
sudo systemctl enable haproxy

# Restart HAProxy service
sudo systemctl restart haproxy

