#!/bin/bash

# Install UFW
sudo apt-get install ufw -y

# Enable UFW
sudo ufw enable

# Allow incoming SSH (port 22), HTTP (port 80), and HTTPS SSL (port 443) traffic
sudo ufw allow ssh
sudo ufw allow http
sudo ufw allow https

# Verify UFW rules
sudo ufw status

